name: kube-yaml-validator
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  scan:
    name: kube-yaml-validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Execute validation script
        run: python main.py example.yaml 'spec.template.spec.containers[*].ports[*].containerPort' 8080
